### ISSUE TITLE
ValueError: read of closed file

### ISSUE THREAD

**Issue by ud2195** [aws-samples/easy-amazon-sagemaker-deployments#1]
While deploying using the below code:-

```
import ezsmdeploy
ez = ezsmdeploy.Deploy(model = 's3://xxxx/ner_model_pubmed.tar.gz',
                  script = '/xxxx/sage_deploy.py',
                  requirements = ['fast-bert'], #or pass in the path to requirements.txt
                  wait = True)

```
i get the below error:-

```
  sudo: no tty present and no askpass program specified
  File "<ipython-input-2-7f8ddbae1725>", line 5, in <module>
    wait = True)

  File "/home/xxx/site-packages/ezsmdeploy/__init__.py", line 207, in __init__
    self.deploy()

  File "/home/xxx/miniconda3/lib/python3.6/site-packages/ezsmdeploy/__init__.py", line 733, in deploy
    self.build_docker()

  File "/home/xxx/miniconda3/lib/python3.6/site-packages/ezsmdeploy/__init__.py", line 491, in build_docker
    self.dockeroutput = p.communicate()[0].decode()

  File "/home/xxx/miniconda3/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()

ValueError: read of closed file
```

kindly help me out

**Comment by w601sxs** [comment]
Something to do with permissions in your environment? The output from docker will be stored in ez.dockeroutput, but it looks like when it tries to read it it does not exist, or is closed, or does not have the permission to do so.

Can you look inside the "src" directory that is generated for a dockerfile. You can try to build the image yourself to see if there are any docker issues.

**Comment by tracthuc** [comment]
The same to me. I can build dockerfile by script manually.

**Comment by antonioortegajr** [comment]
I have the same issue .Looks like this caused by the build-docker.sh using the aws cli version 1 "[get-login](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html)" for ECR which is deprecated. 

`# Get the login command from ECR and execute it directly
$(aws ecr get-login --region ${region} --no-include-email)`

When this fails, the .sh script hangs and the expected files that were to be read, are never created. Thus "ValueError: read of closed file".

 Updating the .sh to use get-login-password (and the rest of the ECR commands for aws cli v2) built the docker image and sent to ECR. I don't see anything in this repo on contributing so not sure how this gets addressed here.

**Comment by w601sxs** [comment]
Thanks Antonio - can you do a PR for this. I need to update the SDK to 2.0 as well and that is in my backlog

**Comment by w601sxs** [comment]
Please check out the new v 1 that fixed this.
